<a href="https://colab.research.google.com/github/jay05Hawk/TensorFlow_all/blob/main/Tensorflow_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.9.2
Keras version: 2.9.0


### GPU/CPU Check

In [3]:
variable = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    #print(var.device.endswith('GPU:0'))
else:
    print('CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


GPU
GPU #0?


### Tensor Constant

In [4]:
smart_science_technology = tf.constant(42)
smart_science_technology

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
smart_science_technology.numpy()

42

In [6]:
smart_science_technology= tf.constant(1, dtype = tf.int64)

smart_science_technology

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [7]:
smart_science_technology_x= tf.constant([[4,2],[9,5]])
print(smart_science_technology_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [8]:

smart_science_technology_x.numpy()

array([[4, 2],
       [9, 5]], dtype=int32)

In [10]:
print('shape:',smart_science_technology_x.shape)
print(smart_science_technology_x.dtype)

shape: (2, 2)
<dtype: 'int32'>


#### Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones & np.zeros

In [11]:
#print(tf.ones(shape=(2,3)))
#print(tf.zeros(shape=(3,2)))
import tensorflow as tf
const2 = tf.constant([[3,4,5], [3,4,5]]);tf
const1 = tf.constant([[1,2,3], [1,2,3]]);
result = tf.add(const1, const2);
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


>We have defined two constants and we add one value to the other. 
>As a result, we got a Tensor object with the result of the adding. 

#### Random constant

In [12]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.6889127 , -0.16874842],
       [ 0.9189842 , -2.259185  ]], dtype=float32)>

In [13]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 0],
       [0, 3]], dtype=int32)>

### Variables

>A variable is a special tensor that is used to store variable values ​​and needs to be initialized with some values

In [14]:
var0 = 24 # python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

>TensorFlow will infer the datatype, defaulting to tf.float32 for floats and tf.int32 for integers

#### The datatype can be explicitly specified

In [15]:
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

$\color{blue}{\text{
`TensorFlow has a large number of built-in datatypes.`}}$
* tf.float16: 16-bit half-precision floating-point.
* tf.float32: 32-bit single-precision floating-point.
* tf.float64: 64-bit double-precision floating-point.
* tf.bfloat16: 16-bit truncated floating-point.
* tf.complex64: 64-bit single-precision complex.
* tf.complex128: 128-bit double-precision complex.
* tf.int8: 8-bit signed integer.
* tf.uint8: 8-bit unsigned integer.
* tf.uint16: 16-bit unsigned integer.
* tf.uint32: 32-bit unsigned integer.
* tf.uint64: 64-bit unsigned integer.
* tf.int16: 16-bit signed integer.
* tf.int32: 32-bit signed integer.
* tf.int64: 64-bit signed integer.
* tf.bool: Boolean.
* tf.string: String.
* tf.qint8: Quantized 8-bit signed integer.
* tf.quint8: Quantized 8-bit unsigned integer.
* tf.qint16: Quantized 16-bit signed integer.
* tf.quint16: Quantized 16-bit unsigned integer.
* tf.qint32: Quantized 32-bit signed integer.
* tf.resource: Handle to a mutable resource.
* tf.variant: Values of arbitrary types.


In [16]:
# To reassign a variable, use var.assign()


var_reassign = tf.Variable(89.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [17]:
var_reassign.assign(98.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [18]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.3112588 ,  0.68996704],
       [ 0.4900487 , -0.98124486]], dtype=float32)>


>We can assign "=" with assign (value), or assign_add (value) with "+ =", or assign_sub (value) with "-="

In [19]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [20]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j]+added_value[i,j]

In [22]:
# Shaping a tensor
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)
tensor

(2, 2, 3)


<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

#### Tensors can be reshaped and retain the same values which is required for constructing Neural networks.

In [23]:
tensor1 = tf.reshape(tensor,[2,6]) # 2 rows 6 cols
#tensor2 = tf.reshape(tensor,[1,12]) # 1 rows 12 cols
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [24]:
tensor2 = tf.reshape(tensor,[1,12]) # 1 row 12 columns
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.]],
      dtype=float32)>

### Rank of a tensor

>The rank of a tensor is defined as the number of dimensions, which is the number of indices that are required to specify any particular element of that tensor.

In [25]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

>(the shape is () because the output here is a scalar value)

In [26]:
# Specifying an element of a tensor


tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

In [27]:
# Casting a tensor to a NumPy variable

print(tensor.numpy())

[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]


In [28]:
print(tensor[1, 0, 2].numpy())

18.0


In [31]:
# Finding the size or length of a tensor

tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [32]:
#the datatype of a tensor
tensor3.dtype

tf.float32

### Tensorflow mathematical operations
>Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU.


In [33]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[-0.6686602   0.13079642]
 [-0.19833125 -0.1670021 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.49145392  0.17056257]
 [ 1.5973315   1.361983  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.1601142  0.301359 ]
 [ 1.3990003  1.1949809]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.3458649  0.09081724]
 [1.9572018  1.4279792 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.3134504 1.3516945]
 [4.051148  3.3034947]], shape=(2, 2), dtype=float32)


### Performing element-wise primitive tensor operations

In [34]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[100., 121., 144.],
        [169., 196., 225.]],

       [[256., 289., 324.],
        [361., 400., 441.]]], dtype=float32)>

### Broadcasting in Tensorflow

>Element-wise tensor operations support broadcasting in the same way that NumPy arrays do.

>The simplest example is multiplication of  a tensor by a scalar value.

In [35]:
tensor4 = tensor*4
print(tensor4)

tf.Tensor(
[[[40. 44. 48.]
  [52. 56. 60.]]

 [[64. 68. 72.]
  [76. 80. 84.]]], shape=(2, 2, 3), dtype=float32)


### Transpose Matrix multiplication

In [36]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])
tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[64]], dtype=int32)>

In [37]:
### Casting a tensor to another datatype


i = tf.cast(tensor1, dtype=tf.int32)
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]], dtype=int32)>

In [38]:
##### Casting with truncation


j = tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

###  Ragged tensors

`A ragged tensor is a tensor having one or more ragged dimensions. Ragged dimensions are dimensions that have slices having various lengths.There are a variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array.`

In [39]:
#constant ragged array

ragged =tf.ragged.constant([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>
tf.Tensor([9 7 4 3], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([11 12  8], shape=(3,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)


### Squared difference of tensors

In [41]:
varx = [4,5,6,1,2]
vary =[8] 
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36], dtype=int32)>

#### Calculate the mean
>Function available
>tf.reduce_mean().

`Similar to np.mean, except that it infers the return datatype from the input tensor, whereas np.mean allows you to specify the output type`

`tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)`

In [42]:
# Defining a constant
numbers = tf.constant([[8., 9.], [1., 2.]])

In [43]:
#### Calculate the mean across all axes

tf.reduce_mean(input_tensor=numbers) #default axis = None

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [44]:
#### Calculate the mean across columns (reduce rows) with this:

tf.reduce_mean(input_tensor=numbers, axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

#### When keepdims = True

In [45]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4.5, 5.5]], dtype=float32)>

In [46]:
#### Calculate the mean across rows (reduce columns) with this:

tf.reduce_mean(input_tensor=numbers, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

In [47]:
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[8.5],
       [1.5]], dtype=float32)>

####  Random values generation